language: node_js
node_js:
  - "12"
cache: yarn

script:
  - echo "Deploy"
  - yarn build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  target_branch: master
  on:
    branch: master
