export const pagesRoutes = [
  ["v-8daa1a0e","/",{"title":"tomosuzu's pages"},["/README.md"]],
  ["v-74bc627b","/about/",{"title":"当サイトについて"},["/about/README.md"]],
  ["v-145ac574","/blog/",{"title":"雑記"},["/blog/README.md"]],
  ["v-53f47c50","/practices/",{"title":"プラクティス一覧について"},["/practices/README.md"]],
  ["v-70e7bf4e","/practices/backlog-refinement.html",{"title":"バックログ・リファイメント"},[":md"]],
  ["v-59517112","/practices/continuous-delivery.html",{"title":"継続的デリバリー"},[":md"]],
  ["v-767f06c6","/practices/continuous-deployment.html",{"title":"継続的デプロイメント"},[":md"]],
  ["v-32b17433","/practices/continuous-integration.html",{"title":"継続的インテグレーション"},[":md"]],
  ["v-94518be8","/practices/daily-standup.html",{"title":"毎日のスタンドアップ・ミーティング"},[":md"]],
  ["v-3b7b0ffc","/practices/empathy-mapping.html",{"title":"共感マッピング"},[":md"]],
  ["v-330ea3a2","/practices/impact-mapping.html",{"title":"インパクトマッピング"},[":md"]],
  ["v-69182e5c","/practices/iteration-planning.html",{"title":"スプリント（イテレーション）計画"},[":md"]],
  ["v-9cfc19c6","/practices/mob-programming.html",{"title":"モブプログラミング"},[":md"]],
  ["v-340747e3","/practices/pair-programming.html",{"title":"ペアプログラミング"},[":md"]],
  ["v-75de6af3","/practices/retrospectives.html",{"title":"ふりかえり（レトロ）"},[":md"]],
  ["v-fea2b9a2","/practices/scrum.html",{"title":"スクラム"},[":md"]],
  ["v-20e5c4f7","/practices/social-contract.html",{"title":"社会契約"},[":md"]],
  ["v-34bd34aa","/practices/team-sentiment.html",{"title":"チーム感情の評価"},[":md"]],
  ["v-a3dd9362","/practices/template.html",{"title":""},[":md"]],
  ["v-a737c9c8","/practices/test-driven-development.html",{"title":"テスト駆動開発"},[":md"]],
  ["v-6acca595","/practices/user-story-mapping.html",{"title":"ユーザーストーリーマッピング"},[":md"]],
  ["v-3c828a2c","/practices/value-stream-process-mapping.html",{"title":"バリューストリーム・プロセスマッピング"},[":md"]],
  ["v-287dbbf8","/practices/visualisation-of-work.html",{"title":"作業の可視化"},[":md"]],
  ["v-d8f9dd24","/scrum/",{"title":"スクラムの教科書"},["/scrum/README.md"]],
  ["v-d3d1c1ea","/scrum/ceremonies.html",{"title":"スクラムのセレモニー"},[":md"]],
  ["v-0112002a","/scrum/roles.html",{"title":"Scrum Roles"},[":md"]],
  ["v-32f72ebc","/blog/2020/JobsToBeDone2.html",{"title":"ジョブ理論に関する考察その２"},[":md"]],
  ["v-1292e632","/blog/2020/%E3%81%82%E3%81%A4%E3%82%82%E3%82%8A.html",{"title":"「あつまれ どうぶつの森」で学ぶプランニングについて"},["/blog/2020/あつもり.html","/blog/2020/あつもり.md",":md"]],
  ["v-0fe39d3e","/blog/2020/%E3%82%B3%E3%83%BC%E3%83%81%E3%83%B3%E3%82%B0%E3%81%AE%E3%81%99%E3%81%B9%E3%81%A6.html",{"title":"コーチングのすべてのレビュー"},["/blog/2020/コーチングのすべて.html","/blog/2020/コーチングのすべて.md",":md"]],
  ["v-4959e9f3","/blog/2019/JobsToBeDone1.html",{"title":"ジョブ理論に関する考察その１"},[":md"]],
  ["v-3706649a","/404.html",{"title":""},[]],
]
